//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUDENTbookServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PostAnswers
    {
        public int answerId { get; set; }
        [Required]
        public int postId { get; set; }
        public int userId { get; set; }
        [RegularExpression("[^#!$%^&*~]*")]
        [Required]
        public string content { get; set; }
        [Required]
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> editedAt { get; set; }
    }
}
