//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STUDENTbookServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class University
    {
        public int universityId { get; set; }
        [Required]
        [RegularExpression("[^#!$%^&*~]*")]
        public string name { get; set; }
        [Required]
        public string city { get; set; }
    }
}
